### ISSUE TITLE
“info” undefined within `onlisten`

### ISSUE THREAD

**Issue by jondashkyle** [shipharbor/merry#86]
getting this lil error:

```
TypeError: Cannot read property 'info' of undefined
at Server.Merry.onlisten (../node_modules/merry/index.js:74:11)
```

this appears to be because the context of `this` within `onlisten` is bound to that of the `server.listen` call. quick and dirty fix is to add this at line 69:

```
this.onlisten = this.onlisten.bind(this)
server.listen(this._port, this.onlisten)
```

unsure if there is an alternate way this should be patched, but a heads up! excited to start using this new version.

**Comment by lrlna** [comment]
Hey! Thanks for reporting, fixed in `5.0.1` :sparkles:
