### ISSUE TITLE
Default route handler not defined

### ISSUE THREAD

**Issue by jondashkyle** [shipharbor/merry#87]
another small one! within the `route` function, we are checking to see if `method` is default:

```
Merry.prototype.route = function (method, route, handler) {
  if (method === 'default') return this.defaultRoute(handler)
```

however, if you check the documentation, the default route only passes a method (default) and a handler (fn). you’ll notice this doesn’t match the arguments anymore, as we’re only passing two args and not three.

a quick fix is to simply use the second arg (route) instead of a third arg for the default method, which is a little funny with naming, but totally doable:

```
Merry.prototype.route = function (method, route, handler) {
  if (method === 'default') return this.defaultRoute(route)
```

really enjoying playing w/ this, and how consistent the api is w/ choo!

**Comment by lrlna** [comment]
you're right again! thanks for all these, Jon <3

fixed in `5.0.2`
