### ISSUE TITLE
unclear how to set default PORT

### ISSUE THREAD

**Issue by mattiaerre** [shipharbor/merry#88]
# Description

following [this example](https://github.com/shipharbor/merry#configuration), it is not possible to have a default `process.env.PORT` for the HTTP server.
it looks like the constructor doesn't take into account the `env` part of the `opts` object:

https://github.com/shipharbor/merry/blob/master/index.js#L22

and the only way to pass a port to the component is when calling the `listen` method:

https://github.com/shipharbor/merry/blob/master/index.js#L64

probably the constructor should store the `env` object and use it if the `listen` method is invoked w/o arguments

```javascript
const merry = require('merry');

const env = { PORT: 8080 };
const app = merry({ env });

app.listen(process.env.PORT);
```
from the terminal

```bash
node index.js
// "port":8080

PORT=1234 node index.js
// "port":1234
```

a possible solution could be:

```javascript
function Merry (opts) {
  /* ... */

  this._env = opts.env || {}
}

Merry.prototype.listen = function (port) {
  if(port === undefined){
    port = this._env.PORT
  }

  /* ... */
}
```

let me know what you think as I maybe miss something 😊 
thanks,

**Comment by mattiaerre** [comment]
// cc @yoshuawuyts @lrlna

**Comment by lrlna** [comment]
hey! sorry I had a bunch of work-work to do today, buttt a #89 is available so take a look!

in terms of the example you started off with, you should be able to do something like this as well:
```js
var merry = require('merry');

var env = { 
  PORT: 8080
};
var app = merry({ env: env });

app.listen(app.env.PORT);
```
( so `app` instead of `process`), but should you wish to leave the param empty and have a `PORT` env obj, you should be able to do that as well.

Let me know if that helps!

**Comment by mattiaerre** [comment]
hi @lrlna and thanks for your reply, I like this API and thanks for the PR as well; I've left some comments 😉
