### ISSUE TITLE
ctx.parse

### ISSUE THREAD

**Issue by yoshuawuyts** [shipharbor/merry#92]
Serializing / deserializing JSON is an API staple. https://github.com/yoshuawuyts/json-stream-to-object was made for fast JSON parsing, think  `ctx.parse` would be good

**Comment by lrlna** [comment]
yea awesome! give me a bit to think about it.

I am concerned about opening up a wormhole for new features on `ctx`, but yea, agree that this is something that we'd basically do every time building out merry apps otherwise.

**Comment by lrlna** [comment]
closed in #94.
