### ISSUE TITLE
Responding with an object has a content type of `json` instead of `application/json`

### ISSUE THREAD

**Issue by alexframe** [shipharbor/merry#99]
If a response is an `object`, a `Content-Type` of `json` is set.

According to the [valid mime types list](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types) on MDN, this should be `application/json`.

It looks like this was changed in 7816e54 - was this intentional?

Should we change this back to conform with MDN?

**Comment by yoshuawuyts** [comment]
yep, should be application/json - PR welcome!

**Comment by lrlna** [comment]
yep! totally missed this in the rewrite; got it fixed in #100 tho

**Comment by lrlna** [comment]
@alexframe lemme know if it's all good ^___^

**Comment by alexframe** [comment]
Look good @lrlna! Thanks.

**Comment by lrlna** [comment]
Awesome! I merged those two in as well. Thanks! :) I am gonna add you as a contributor :sparkles:
